name: Deploy to developers enviroment
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  deploy-to-devs-envs:
    # Name the Job
    name: Deploy to developers enviroment
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release-notes'
          
      - uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: release-notes
